name: Run tests on all supported platforms

on:
  pull_request: ~
  workflow_dispatch: ~

jobs:
  test:
    name: Run test on ${{ matrix.os }} with ${{ matrix.py_ver }}
    strategy:
      matrix:
        os: 
          - macOS-latest
          - macos-11
          - ubuntu-latest
          - ubuntu-20.04
          - windows-latest
          - windows-2019
    
    runs-on: ${{ matrix.os }}
    if: ${{ ! github.event.pull_request.draft }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Run tests
        run: python -m pytest
