name: Run tests on Windows
on:
  pull_request:

jobs:
  test:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.5'
          architecture: 'x64'

      - name: Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install pipenv
        run: python -m pip install --upgrade pipenv

      - name: Create .venv folder
        run: New-Item -ItemType Directory -Force -Path .\.venv

      # Cache dependencies. Ref:
      # https://github.com/actions/cache/blob/master/examples.md#python---pip
      # https://github.com/pypa/pipenv/issues/4586#issuecomment-807695864
      - name: Cache Dependencies
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: .\.venv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          pipenv install --dev --verbose
          pipenv install atomicwrites 

      - name: Run tests
        run: pipenv run python -m pytest